version: "3.8"

services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: database_user
      POSTGRES_PASSWORD: your_database_password
      POSTGRES_DB: database
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      PGUSER: database_user
      PGPASSWORD: your_database_password
      PGDATABASE: database
      PGHOST: database
      PGPORT: 5432
      DATABASE_URL: postgres://database_user:your_database_password@database:5432/database # The database URL

    depends_on:
      - database
    ports:
      - "5001:5001"
    volumes:
      - ./database/sql:/app/database/sql
      - ./backend/:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app
    ports:
      - "3000:3000"

volumes:
  db_data:
